### ISSUE TITLE
Gammix Project Merge

### ISSUE THREAD

**Issue by Zorono** [Southclaws/progress2#27] opened 2019-03-12 06:35 UTC
Hello dude, Good job and thanks for sharing your efforts....
but unfortunately i am still not intersted in y_iterate/y_hooks as it requires too many libs from YSI(y_remote,y_core,_y_cgen,y_hooks...) which takes a size on my server(big AMX file) and slows down my server so it'd be great if you merged gammix's fork with yours(https://github.com/Agneese-Saini/SA-MP/blob/master/pawno/include/progress.inc) as it doesn't require YSI and includes too many new features as an optional version of your project for those who aren't interested in YSI like me... Thanks for your patience and i wish to agree.

**Comment by Southclaws** [comment] 2019-03-12 08:23
Why does a large AMX binary matter? How large is it? What parts of YSI are supposedly affecting runtime performance? I've never seen this before or heard anyone else have this issue. I used YSI for many years (6 or 7 iirc) and never had any measurable performance impact.

If you really care about performance, you'd have noticed that the fork you linked is much worse. Not that it matters at all, we're talking about nanoseconds here.

But, I'd be happy to take a PR with a better implementation I just see no real value in reinventing the wheel when it comes to fundamental data structures such as iterators. This is the reason I built sampctl, so your installation effort doesn't scale with the number of dependencies.

**Comment by Zorono** [comment] 2019-03-12 08:37
it matters when i'm going to upload it with low quality Internet Connection(it takes 1 hour and might face upload failure due to some connection outages)
 What parts of YSI are supposedly affecting runtime performance? really i couldn't detect the affecting part as much as it seems it to be clearly caused by YSI(the problem didn't appear until i used YSI)

**Comment by Crayder** [comment] 2019-03-12 12:17
The problem is probably occurring by how you're using it then... what are you using from YSI and can you provide examples?

Also you just told us the YSI AMX is smaller than the original...

You are likely just going by something you've heard, just try it. Run some benchmarks on things you believe it is affecting, if you want I'll even help you do so. Just uh, tell us what performance issues YSI is causing.

**Comment by Southclaws** [comment] 2019-03-12 13:01
[Open an issue on the YSI repository](https://github.com/pawn-lang/YSI-Includes/issues/new) to discuss your issues with YSI and contribute to a fix.

Since this isn't an immediate problem with this library, I'm closing this for now as writing a linked list implementation from scratch is way out of scope for this library.

**Closed as completed by Southclaws** 2019-03-12 13:01 UTC

**Comment by MuthaX** [comment] 2022-08-20 09:10
@Zorono, since #41 Y-libs are optional.
